export const PLATFORM_AUDIT_ACTIONS = [
    "platform.auth.login_success",
    "platform.auth.login_failure",
    "platform.auth.mfa_failure",
    "platform.auth.logout",
    "platform.company.created",
    "platform.company.updated",
    "platform.company.suspended",
    "platform.company.reactivated",
    "platform.channel.created",
    "platform.channel.updated",
    "platform.channel.credentials_updated",
    "platform.channel.status_changed",
    "platform.subscription.plan_changed",
    "platform.subscription.overage_changed",
    "platform.billing.settings_updated",
    "platform.billing.courtesy_trial_granted",
    "platform.billing.checkout_ensured",
    "platform.impersonation.started",
    "platform.impersonation.ended",
    "platform.user.created",
    "platform.user.role_changed",
    "platform.user.deactivated",
    "platform.feature_flag.created",
    "platform.feature_flag.updated",
    "platform.feature_flag.override_set",
    "platform.feature_flag.override_removed",
    "platform.audit.exported",
    "platform.audit.archived",
    "platform.access.denied",
] as const;

export type PlatformAuditAction = (typeof PLATFORM_AUDIT_ACTIONS)[number];
